### ISSUE TITLE
Channel names 1 character too short

### ISSUE THREAD

**Issue by cawmit** [sawyerf/Youtube_subscription_manager#5]
I'm finding that the channel names are 1 character too short, the last one is cut off. It's this line that is responsible, is there a reason for this to be here?  https://github.com/sawyerf/Youtube_subscription_manager/blob/71add4cb28213dc982643bd8ac854d996fdacf91/youtube_sm/src/swy.py#L49

**Comment by sawyerf** [comment]
Thank you I correct that
