### ISSUE TITLE
can't add subscriptions

### ISSUE THREAD

**Issue by Joseph65** [sawyerf/Youtube_subscription_manager#8]
i keep getting thiis error when adding subscriptions 
    youtube-sm -a https://www.youtube.com/channel/UC15j7WaRfrSDHD6OzPqLFJg
    [!] The channel/playlist can't be add. It could be delete.
    [!] Failed to add https://www.youtube.com/channel/UC15j7WaRfrSDHD6OzPqLFJg

channel is online

**Comment by sawyerf** [comment]
Hello,
It work fine for me.
Can you send me the result of the command:
 `youtube-sm -a https://www.youtube.com/channel/UC15j7WaRfrSDHD6OzPqLFJg -v `

**Comment by Joseph65** [comment]
it's working now, thanks 
here is the log 

[*] Hello :)
[*] Date: 2021-05-14 14:22:30.450133
[*] Version: 2021.04.13
[*] Path: /home/user/.cache/youtube_sm/
[*] Start read swy
[*] 10 subs for [youtube]
[*] GET http://www.youtube.com/feeds/videos.xml?channel_id=UC15j7WaRfrSDHD6OzPqLFJg 200 24890 0.2934248447418213
[*] Add: UC15j7WaRfrSDHD6OzPqLFJg	Rafa
[*] Start read swy
[*] 10 subs for [youtube]
[*] Done (0.32779 seconds)
